# Generated by Django 5.2.4 on 2025-08-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firebase_uid",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("conversations", models.TextField(default="[]")),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserExerciseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firebase_uid", models.CharField(db_index=True, max_length=128)),
                ("exercise_type", models.CharField(max_length=50)),
                ("topic", models.CharField(max_length=100)),
                ("total_questions", models.IntegerField()),
                ("correct_answers", models.IntegerField()),
                ("score", models.FloatField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "User Exercise Progress",
                "indexes": [
                    models.Index(
                        fields=["firebase_uid"], name="english_exa_firebas_367756_idx"
                    ),
                    models.Index(
                        fields=["exercise_type", "topic"],
                        name="english_exa_exercis_25e598_idx",
                    ),
                ],
            },
        ),
    ]
