# Generated by Django 5.2.4 on 2025-08-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("english_exam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VocabularyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "topic",
                    models.CharField(
                        help_text="Chủ đề từ vựng (ví dụ: 'gia-dinh', 'dong-vat')",
                        max_length=100,
                    ),
                ),
                (
                    "question_text",
                    models.TextField(help_text="Nội dung câu hỏi từ vựng"),
                ),
                ("option_a", models.CharField(max_length=255)),
                ("option_b", models.CharField(max_length=255)),
                ("option_c", models.CharField(max_length=255)),
                ("option_d", models.CharField(max_length=255)),
                (
                    "correct_answer",
                    models.CharField(
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                    ),
                ),
                (
                    "explanation",
                    models.TextField(
                        blank=True, help_text="Giải thích đáp án (tùy chọn)", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Câu hỏi từ vựng",
                "verbose_name_plural": "Câu hỏi từ vựng",
            },
        ),
    ]
